### ISSUE TITLE
Windows下使用报错，解码问题

### ISSUE THREAD

**Issue by nod0by** [kuboRenka/scanman#2]
Windows下报错UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 712: illegal multibyte sequence.
建议在/scanman/core.py第87行的open函数增加‘rb’参数。

**Comment by rxzzh** [comment]
感谢issue😗，'rb'参数已加入，在commit b20042cc767e199797e9914b2e0ab227fc8f12b6 中尝试修复了这一问题。
